django/django_1017/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

django/django_1017/django_1017/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

django/django_1017/articles/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail, ResizeToFill

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=80)
    content = models.TextField()
    image = models.ImageField(blank=True, upload_to='images/')
    thumbnail = ProcessedImageField(upload_to='images/', blank=True,
                                           processors=[ResizeToFill(100, 50)],
                                           format='JPEG',
                                           options={'quality':60})
    

django/django_1017/articles/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = '__all__'

django/django_1017/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from .forms import ArticleForm

# Create your views here.
def index(request):
    articles = Article.objects.all()
    return render(request, 'articles/index.html', {'articles' : articles})

def detail(request, pk):
    article = Article.objects.get(pk=pk)
    return render(request, 'articles/detail.html', {'article' : article})

def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        form = ArticleForm()
    return render(request, 'articles/create.html', {'form' : form})

def update(request, pk):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES, instance=Article.objects.get(pk=pk))
        if form.is_valid():
            form.save()
            return redirect('articles:detail', pk)
    else:
        form = ArticleForm(instance=Article.objects.get(pk=pk))
    return render(request, 'articles/update.html', {'form' : form})

def delete(request, pk):
    article = Article.objects.get(pk=pk)
    if request.method == 'POST':
        article.delete()
        return redirect('articles:index')
    else:
        return redirect('articles:detail', pk)        

django/django_1017/articles/templates/articles/create.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}

<form action="{% url 'articles:create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <div class='d-flex justify-content-end'>
        {% bootstrap_button button_type="submit" content="제출하기" %}
    </div>
</form>

{% endblock content %}

django/django_1017/articles/templates/articles/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}

<p>{{ article.title }}</p>
<p>{{ article.content }}</p>
{% if article.image %}
<img src="{{ article.image.url }}" alt="{{ article.image }}">
{% endif %}
{% if article.thumbnail %}
<img src="{{ article.thumbnail.url }}" alt="{{ article.thumbnail }}" width='400' height='300'>
{% endif %}

<form class='d-flex justify-content-end' action="{% url 'articles:delete' article.pk %}" method='POST'>
    {% csrf_token %} 
    <a class='btn btn-outline-dark mx-1' href="{% url 'articles:update' article.pk %}">수정하기</a>
    <input class='btn btn-outline-dark mx-1' type='submit' value='삭제'>
</form>

{% endblock content %}

django/django_1017/articles/templates/articles/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
{% for article in articles %}
<a href="{% url 'articles:detail' article.pk %}"><p>{{ article.title }}</p></a>
<p>{{ article.content }}</p>
{% comment %} {% if article.image %}
<img src="{{ article.image.url }}" alt="{{ article.image }}">
{% endif %} {% endcomment %}
{% if article.thumbnail %}
<img src="{{ article.thumbnail.url }}" alt="{{ article.image }}">
{% endif %}
{% endfor %}
<a href="{% url 'articles:create' %}">글 작성</a>
<a class="btn btn-primary my-3" href="{% url 'articles:create' %}">글 쓰기</a>

{% endblock content %}

django/django_1017/articles/templates/articles/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}

<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <div class='d-flex justify-content-end'>
        {% bootstrap_button button_type="submit" content="제출하기" %}
    </div>
</form>

{% endblock content %}

django/django_1017/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>되냐?</h1>
    {% block content %}
    {% endblock content %}
</body>
</html>