django/django_0928/django_0928/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todos.urls'))
]

django/django_0928/todos/urls.py
from django.urls import path
from . import views

app_name = 'todos'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('delete/<int:todo_pk>', views.delete, name='delete'),
    path('update/<int:todo_pk>', views.update, name='update'),
    path('detail/<int:todo_pk>', views.detail, name='detail'),
    path('edit/<int:todo_pk>', views.edit, name='edit'),
    path('upload/<int:todo_pk>', views.upload, name='upload')
]

django/django_0928/todos/models.py
from email.policy import default
from django.db import models

# Create your models here.
class Todo(models.Model):
    content = models.CharField(max_length=80)
    completed = models.BooleanField(default=False)
    priority = models.IntegerField(default=3)
    created_at = models.DateField(auto_now_add=True)
    deadline = models.DateField(null=True)
    
    

django/django_0928/todos/views.py
from django.shortcuts import render, redirect
from .models import Todo

# Create your views here.
def index(request):
    todos = Todo.objects.all()
    context = {
        'todos' : todos
    }
    return render(request, 'todos/index.html', context)

def create(request):
    todo = request.GET
    content = todo['content']
    priority = todo['priority']
    deadline = todo['deadline']
    if todo['priority'] == 'select_value' and todo['deadline'] == '':
        Todo.objects.create(content=content)
    elif todo['priority'] == 'select_value':
        Todo.objects.create(content=content, deadline=deadline)
    elif todo['deadline'] == '':
        Todo.objects.create(content=content, priority=priority)
    else:
        Todo.objects.create(content=content, priority=priority, deadline=deadline)
    
    todos = Todo.objects.all()
    context = {
        'todos' : todos
    }
    return redirect('todos:index')

def delete(request, todo_pk):
    d = Todo.objects.get(pk = todo_pk)
    d.delete()
    return redirect('todos:index')

def update(request, todo_pk):
    u = Todo.objects.get(pk = todo_pk)
    if u.completed == False:
        u.completed = True
    else:
        u.completed = False
    u.save()
    return redirect('todos:index')

def detail(request, todo_pk):
    todo = Todo.objects.get(pk = todo_pk)
    context = {
        'todo' : todo
    }
    return render(request, 'todos/detail.html', context)

def edit(request, todo_pk):
    todo = Todo.objects.get(pk = todo_pk)
    context = {'todo': todo}
    return render(request, 'todos/edit.html', context)

def upload(request, todo_pk):
    todo = Todo.objects.get(pk = todo_pk)
    content = request.GET.get('content')
    todo.content = content
    todo.save()
    return redirect('todos:detail', todo_pk)

django/django_0928/todos/templates/todos/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <h1 class="text-center fw-bolder">상세 보기</h1>
    <table class='table table-boredred'>
        <thead>
            <tr>
                <th>우선 순위</th>
                <th>할 일</th>
                <th>생성 날짜</th>
                <th>마감 기한</th>
                <th>진행 상태</th>
            </tr>    
        </thead>
        <tbody>
            <tr>
                <th>{{ todo.priority }}</th>
                <th>{{ todo.content }}</th>
                <th>{{ todo.created_at }}</th>
                <th>{{ todo.deadline }}</th>
                <th>{{ todo.completed }}</th>
            </tr>    
        </tbody>
    </table>
    <a class='btn btn-primary d-grid' href="{% url 'todos:index' %}">홈으로</a>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</body>
</html>

django/django_0928/todos/templates/todos/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <h1 class="text-center fw-bolder">수정하기</h1>
    <form action="{% url 'todos:upload' todo.pk %}">
        <div class="input-group flex-nowrap my-3">
            <span class="input-group-text" id="addon-wrapping">할 일</span>
            <input name="content" maxlength ='10' type="text" class="form-control" value="{{ todo.content }}">
        </div>
        <div class="d-grid my-3">
            <select name="priority">
                <option selected value="select_value">select value</option>
                <option value=1>1</option>
                <option value=2>2</option>
                <option value=3>3</option>
                <option value=4>4</option>
                <option value=5>5</option>
            </select>
        </div>
        <div class="d-grid my-3">
            <input name="deadline" type="date" value="{{ todo.deadline.isoformat }}">
        </div>
        <div class="d-grid my-3">
            <input class="btn btn-outline-primary" type="submit" value="수정하기">
        </div>
    </form>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</body>
</html>

django/django_0928/todos/templates/todos/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <title>Document</title>
</head>
<body>
    <h1 class="text-center fw-bolder">오늘 할 일을 내일로 미루지 말자</h1>
    <!-- 할 일 추가 -->
    <div class="container">
        <form action="{% url 'todos:create' %}">
            <div class="input-group flex-nowrap my-3">
                <span class="input-group-text" id="addon-wrapping">할 일</span>
                <input name="content" maxlength ='10' type="text" class="form-control">
            </div>
            <div class="d-grid my-3">
                <select name="priority">
                    <option selected value="select_value">select value</option>
                    <option value=1>1</option>
                    <option value=2>2</option>
                    <option value=3>3</option>
                    <option value=4>4</option>
                    <option value=5>5</option>
                </select>
            </div>
            <div class="d-grid my-3">
                <input name="deadline" type="date">
            </div>
            <div class="d-grid my-3">
                <input class="btn btn-outline-primary" type="submit" value="할 일 추가">
            </div>
        </form>
        <!-- 투두리스트 -->
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th scope="col">우선 순위</th>
                    <th scope="col">할 일</th>
                    <th scope="col">생성 날짜</th>
                    <th scope="col">마감 기한</th>
                    <th scope="col">진행 상태</th>
                    <th scope="col">상태 변경</th>
                    <th scope="col">삭제</th>
                </tr>
            </thead>
            <tbody>
                {% for todo in todos %}
                    <tr>
                        {% if todo.completed == True %}
                            <td><s>{{ todo.priority }}</s></td>
                            <td><s><a class="text-decoration-none" href="{% url 'todos:detail' todo.pk %}">{{ todo.content }}</a></s><a type="button" class="btn btn-sm btn-outline-primary" href="{% url 'todos:edit' todo.pk %}">수정</a></td>
                            <td><s>{{ todo.created_at.year }}년 {{ todo.created_at.month }}월 {{ todo.created_at.day}}일</s></td>

                            {% if todo.deadline == null %}
                                <td><s>None</s></td>
                            {% else %}
                                <td><s>{{ todo.deadline.year }}년 {{ todo.deadline.month }}월 {{ todo.deadline.day}}일</s></td>
                            {% endif %}
                            
                            {% if todo.completed == True %}
                                <td><i class="bi bi-check-square-fill"></i></td>
                            {% else %}
                                <td><i class="bi bi-square"></i></td>
                            {% endif %}
                        {% else %}
                            <td>{{ todo.priority }}</td>
                            <td><a class="text-decoration-none" href="{% url 'todos:detail' todo.pk %}">{{ todo.content }}</a><a type="button" class="btn btn-sm btn-outline-primary" href="{% url 'todos:edit' todo.pk %}">수정</a></td>
                            <td>{{ todo.created_at.year }}년 {{ todo.created_at.month }}월 {{ todo.created_at.day}}일</td>

                            {% if todo.deadline == null %}
                                <td>None</td>
                            {% else %}
                                <td>{{ todo.deadline.year }}년 {{ todo.deadline.month }}월 {{ todo.deadline.day}}일</td>
                            {% endif %}
                            
                            {% if todo.completed == True %}
                                <td><i class="bi bi-check-square-fill"></i></td>
                            {% else %}
                                <td><i class="bi bi-square"></i></td>
                            {% endif %}
                        {% endif %}
                        <td><a type="button" class="btn btn-primary" href="{% url 'todos:update' todo.pk %}">수정</a></td>
                        <td><a type="button" class="btn btn-danger" href="{% url 'todos:delete' todo.pk %}">삭제</a></td>
                    </tr>
                {% endfor %}    
            </tbody>
        </table>
    </div>
   
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</body>
</html>