django/django_1011/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('index/', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<int:pk>', views.detail, name='detail'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('delete/', views.delete, name='delete'),
    path('<int:pk>/follow/', views.follow, name='follow'),
]

django/django_1011/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/comments/', views.comment_create, name='comment_create'),
    path('<int:article_pk>/comments/<int:comment_pk>/update/', views.comment_update, name='comment_update'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:article_pk>/like/', views.like, name='like'),
    
]

django/django_1011/django_1011/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

django/django_1011/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')
    @property
    def full_name(self):
        return f'{self.last_name}{self.first_name}'

django/django_1011/articles/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail, ResizeToFill

# Create your models here.
class Article(models.Model):
    # Article과 User는 n:1관계, user FK를 넣음
    # accounts 앱에서 User모델 참조
    # user가 탈퇴하면 글도 다 삭제되는걸로
    # settings.AUTH_USER_MODEL로 해도 되는듯
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(blank=True, upload_to='images/')
    # If you only want to save the processed image (without maintaining the original)
    # ImageSpecField는 원본도 같이 저장하는듯...
    # ResizeToFill : 설정한 사이즈에 딱 맞춰서 이미지 크기 수정
    # ResizeToFit : 비율 유지한 채로 이미지 크기 수정
    thumbnail = ProcessedImageField(upload_to='images/', blank=True,
                                           processors=[ResizeToFill(100, 50)],
                                           format='JPEG',
                                           options={'quality':60})
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name = 'like_articles')
    
class Comment(models.Model):
    # models.ForeighKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    article = models.ForeignKey('Article', on_delete=models.CASCADE)
    content = models.CharField(max_length=80)
    image = ProcessedImageField(upload_to='images/', blank=True,
                                           processors=[ResizeToFill(300, 300)],
                                           format='JPEG',
                                           options={'quality':90})
    
    

django/django_1011/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

# 비밀번호 두개를 받아서 일치하는 로직이 포함된 폼
class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'last_name', 'first_name')
        help_texts = {
            'username' : '',
            'email' : '',
            'password' : '' 
        }

# 비밀번호 두 개를 받을 필요가 없는 폼?
class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'last_name', 'first_name')
        

django/django_1011/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import CustomUserCreationForm, CustomUserChangeForm
from .models import User
from django.contrib import messages
from django.contrib.auth import get_user_model, update_session_auth_hash
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    users = get_user_model().objects.all()
    context = {'users' : users}
    return render(request, 'accounts/index.html', context)

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            # 회원가입 후 곧바로 로그인
            auth_login(request, user)
            return redirect('articles:index')
    else:
        form = CustomUserCreationForm()
    context = {'form' : form,}
    return render(request, 'accounts/signup.html', context)

def detail(request, pk):
    user = get_user_model().objects.get(pk = pk)
    return render(request, 'accounts/detail.html', {'user': user})

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'articles:index')
    else:
        form = AuthenticationForm()
    context = {'form' : form}
    return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('articles:index')

@login_required
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('accounts:detail', request.user.pk)
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {'form' : form,}
    return render(request, 'accounts/update.html', context)

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            # 암호 변경 시 변경된 암호로 다시 로그인 상태 유지, 즉 세션 무효화 방지하기
            # from django.contrib.auth import update_session_auth_hash
            # update_session_auth_hash(request, form.user)
            return redirect('accounts:login')
    else:
        form = PasswordChangeForm(request.user)
    context = {'form': form, }
    return render(request, 'accounts/change_password.html', context)

def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect('articles:index')    

@login_required
def follow(request, pk):
    # 프로필에 해당하는 유저를 로그인한 유저가!
    user = get_object_or_404(get_user_model(), pk=pk)
    if request.user == user:
        messages.warning(request, '스스로 팔로우 할 수 없습니다.')
        return redirect('accounts:detail', pk)
    if request.user in user.followers.all():
    # (이미) 팔로우 상태이면, '팔로우 취소'버튼을 누르면 삭제 (remove)
        user.followers.remove(request.user)
    else:
    # 팔로우 상태가 아니면, '팔로우'를 누르면 추가 (add)
        user.followers.add(request.user)
    return redirect('accounts:detail', pk)     
        

django/django_1011/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<div class='container'>
    <h1 class='text-center my-3'>비밀번호 변경하기</h1>
    <form action='' method='POST'>
    {% csrf_token %}
    {% bootstrap_form form %}
    <div class='d-flex justify-content-between'>
        {% bootstrap_button button_type='submit' content='변경하기' %}
        <a class='btn btn-primary btn-sm' href="{% url 'accounts:detail' request.user.pk %}">취소</a>
    </div>
    </form>
<div>
{% endblock content %}

django/django_1011/accounts/templates/accounts/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% block content %}
<!-- Button trigger modal -->
<div class='d-flex my-3 justify-content-center'>
  <button type="button" class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#detail">정보 보기</button>

  <!-- Modal -->
  <div class="modal fade" id="detail" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">회원 정보</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <table class='table'>
            <tbody>
              {% if user.is_superuser %}
              <tr>
                <th scope='row'>등급</th>
                <td>관리자</td>
              </tr>
              {% else %}
              <tr>
                <th scope='row'>등급</th>
                <td>일반 회원</td>
              </tr>
              {% endif %}
              <tr>
                <th scope='row'>아이디</th>
                <td>{{ user.username }}</td>
              </tr>
              <tr>
                <th scope='row'>이름</th>
                <td>{{ user.full_name }}</td>
              </tr>
              <tr>
                <th scope='row'>이메일</th>
                <td>{{ user.email }}</td>
              </tr>
              <tr>
                <th scope='row'>가입일</th>
                <td>{{ user.date_joined|date:'y년 m월 d일' }}</td>
              </tr>
              <tr>
                <th scope='row'>마지막 로그인</th>
                <td>{{ user.last_login|date:'y년 m월 d일 f:s' }}</td>
              </tr>
              <tr>
                <th scope='row'>팔로우/팔로잉</th>
                <td>{{ user.followings.count }}/{{ user.followers.count }}</td>
              </tr>
            </tbody>
          </table>
          {% if request.user != user %}
          <a href="{% url 'accounts:follow' user.pk %}">
            {% if request.user in user.followers.all %}
                팔로우 취소
            {% else %}
                팔로우
            {% endif %}
          </a>
          {% endif %}
        </div>
        <div class='modal-footer'>
          <div class='container d-flex justify-content-between my-3'>
            {% if request.user.is_superuser and request.user == user %}
            <div>
              <a class='btn btn-primary btn-sm' href="{% url 'accounts:change_password' %}">비밀번호 변경</a>
              <a class='btn btn-primary btn-sm' href="{% url 'accounts:update' %}">정보 수정</a>
            </div>
            {% elif request.user == user %}
            <div>
              <a class='btn btn-primary btn-sm' href="{% url 'accounts:change_password' %}">비밀번호 변경</a>
              <a class='btn btn-primary btn-sm' href="{% url 'accounts:update' %}">정보 수정</a>
            </div>
            <a class='btn btn-danger btn-sm' data-bs-toggle="modal" data-bs-target="#exampleModal">탈퇴하기</a>
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h1 class="modal-title fs-5" id="exampleModalLabel">탈퇴하기</h1>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                      정말로 탈퇴하시겠습니까?
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                      <a class='btn btn-primary' href="{% url 'accounts:delete' %}">탈퇴하기</a>
                    </div>
                  </div>
                </div>
            </div>
            {% endif %}
        </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class='container border my-3 fs-4'>
  <div class='row'>
    <div class='col p-3'>
      <h1 class='text-center'>{{ user.username }}님이 작성한 글</h1>
      {% for article in user.article_set.all %}
      <hr>
      <p class='fs-6'><a class='text-decoration-none' href="{% url 'articles:detail' article.pk %}">{{ article.title }}</a> | {{ article.created_at|date:'y/m/d' }}</p>
      {% endfor %}
    </div>
    <div class='col p-3'>
      <h1 class='text-center'>{{ user.username }}님이 작성한 댓글</h1>
      {% for comment in user.comment_set.all %}
      <hr>
      <p class='fs-6'><a class='text-decoration-none' href="{% url 'articles:detail' comment.article.pk %}">{{ comment.article.title }}</a> | {{ comment.content }}</p>
      {% endfor %}
    </div>
  </div>
    
    
    
    
</div>

{% endblock content %}

django/django_1011/accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
<h1 class='text-center my-3'>회원 리스트<h1>
<div class='container fs-6'>
    <table class='table'>
        <thead>
            <tr>
                <th scope='col'>pk</th>
                <th scope='col'>username</th>
                <th scope='col'>name</th>
                <th scope='col'>email</th>
                <th scope='col'>date_joined</th>
                <th scope='col'>last_login</th>
                <th scope='col'>is_superuser</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td><a class='text-decoration-none' href = {% url 'accounts:detail' user.pk %}>{{ user.username }}</td>
                <td>{{ user.last_name }}{{ user.first_name }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.date_joined }}</td>
                <td>{{ user.last_login }}</td>
                {% if user.is_superuser %}
                <td>관리자</td>
                {% else %}
                <td></td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock content %}

django/django_1011/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<div class='container'>
    <form action='' method='POST'>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type='submit' content='로그인' %}
    </form>
<div>
{% endblock content %}

django/django_1011/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}

<h1 class='text-center my-3'>회원가입</h1>
<div class='container'>
    <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" content="가입하기" %}
    </form>
</div>
{% endblock content %}

django/django_1011/accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<div class='container'>
    <h1 class='text-center my-3'>회원정보 수정하기</h1>
    <form action='' method='POST'>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type='submit' content='수정하기' %}
    </form>
<div>
{% endblock content %}