django/django_1011/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('index/', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<int:pk>', views.detail, name='detail'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('delete/', views.delete, name='delete'),
    path('<int:pk>/follow/', views.follow, name='follow'),
]

django/django_1011/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/comments/', views.comment_create, name='comment_create'),
    path('<int:article_pk>/comments/<int:comment_pk>/update/', views.comment_update, name='comment_update'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:article_pk>/like/', views.like, name='like'),
    
]

django/django_1011/django_1011/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

django/django_1011/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <title>Document</title>
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
</head>
<body>
    <nav class='navbar bg-success bg-opacity-25'>
        <div class='container-fluid justify-content-between'>
            {% if request.user.is_authenticated %}
                {% if request.user.is_superuser %}
                <div>
                    <a class='btn btn-primary btn-sm' href="{% url 'accounts:detail' request.user.pk %}">내 정보</a>
                </div>
                <a href="{% url 'articles:index' %}" class='fs-5 text-dark text-decoration-none'><p>{{ request.user }}님, 환영합니다</p></a>
                <div>
                    <a class='btn btn-primary btn-sm' href="{% url 'accounts:logout' %}">로그아웃</a>
                </div>
                {% else %}
                <a class='btn btn-primary btn-sm' href="{% url 'accounts:detail' request.user.pk %}">내 정보</a>
                <a href="{% url 'articles:index' %}" class='fs-5 text-dark text-decoration-none'><p>{{ request.user }}님, 환영합니다</p></a>
                <div>
                    <a class='btn btn-primary btn-sm' href="{% url 'accounts:logout' %}">로그아웃</a>
                </div>
                {% endif %}
            {% else %}
            <a class='btn btn-primary btn-sm' href="{% url 'accounts:signup' %}">회원가입</a>
            <a class='btn btn-primary btn-sm' href="{% url 'accounts:login' %}">로그인</a>
            {% endif %}
        </div>
    </nav>



    {% block content %}
    {% endblock content %}
    {% bootstrap_javascript %}
</body>
</html>